# The proposal
<!--
This is where the proposal should be outlined. 
-->

## Overview
<!--
At a high-level address what your proposal is and how it will address the problem identified. Highlight any benefits to the R Community that follow from solving the problem. This should be your most compelling section.
-->


Using the support from this proposal, we will take our existing tool for calculating volatility of compounds and expand its usage to makes predictions for essentially any compound, and enable researchers in a wide variety of fields to be able to use it with ease. 
The current version of `volcalc` can estimate volatility only for compounds in one chemical database, the Kyoto Encyclopedia of Genes and Genomes (KEGG).
However, by refactoring existing code, we can make the volatility prediction functionality available to essentially any compound that has a known structure.
Additionally, we plan to improve package infrastructure and documentation (i.e. tests, CI, vignettes, etc.), build the package on r-universe, and submit the package to CRAN in order to simplify installation and make the package easier for users to find and use.

## Detail
<!--
Go into more detail about the specifics of the project and it delivers against the problem.

Depending on project type the detail section should include:

 - [ ] Minimum Viable Product
 - [ ] Architecture
 - [ ] Assumptions
-->

The current version of `volcalc` was created in 2022 as part of a [data science incubator](https://datascience.cct.arizona.edu/cct-data-science-incubator) project in collaboration between Dr. Kristina Riemer and Dr. Laura Meredith at University of Arizona.
`volcalc` is the first project, to our knowledge, to implement the SIMPOL method for predicting chemical vapor pressures and enthalpies of vaporization [@pankowSIMPOLSimpleGroup2008] in an R package.
This current version of the `volcalc` package has been successfully used to calculate volatility estimates for *all* 16,000+ compounds in the KEGG database [@meredith]. 
To ensure accuracy of the package, the volatility estimates for a subset of the compounds were validated using hand-collected data [@meredith2022; @honeker2021]. 

Because `volcalc` is currently limited to only working with chemical compounds from KEGG, we will refactor it to take chemical compound structure files as inputs directly.
The type of structure file the packagee uses is called a molfile. 
The main function in `volcalc`, `calc_vol()`, currently downloads chemical information as molfiles from the KEGG API as a starting point.
It reads in that molfile and parses it to find functional groups.
It finally applies an algorithm (published in @pankowSIMPOLSimpleGroup2008) to predict vapor pressure, and outputs to the user a relative measure of volatility.

A molfile is an open format, and various tools exist to translate other standard representations of chemical structure such as SMILES [@weininger1988smiles] and InChI [@heller2013] to molfiles. 
This translation can be done using the [`OpenBabel`](http://openbabel.org/wiki/Main_Page) command line utility or in R with [`ChemmineOB`](https://github.com/girke-lab/ChemmineOB).
Since `ChemmineOB` is already a dependency of `volcalc`, we can additionally extend `volcalc` to allow other representations of chemical structures as inputs.
Since SMILES and InChl are both string representations, this will ideally make `volcalc` fit more easily into a `data.frame`-based workflow.

Refactoring the code in `volcalc` to work with essentially any chemical and preparing the package for wider distribution will make this powerful tool accessible to researchers across a variety of domains.

`volcalc` is developed on GitHub and distributed under an MIT license.
Project repository: <https://github.com/Meredith-Lab/volcalc>

### Project Goals

Our goals for the proposed project fall into two main categories: 1) to make `volcalc` useful for applications beyond estimating relative volatility for compounds in the KEGG database, and 2) polishing the package in preparation for an initial submission to CRAN.

For the first goal, we will focus on decoupling the data access and volatility estimation functionality of existing code in the `volcalc` package.
This code is already written and the main work here is in API design and re-factoring.
The **first minimum viable product** is a function that can calculate volatility when provided a path to a molfile and a package vignette demonstrating how to couple this with chemical data sources such as the `webchem` package.

The second goal will involve improving test coverage (although current coverage is high at 96.88% as reported by `covr::package_coverage()`), establishing continuous integration with GitHub Actions, improving documentation, and satisfying `R CMD check`.
The **second minimum viable product** is a package that has gone through the steps suggested by `usethis::use_release_issue()` and is ready to submit to CRAN.

A reach goal is to allow users to input other representations of chemical structure besides molfiles.
The `ChemmineOB` package can translate a variety of representations of chemical structure to molfiles and is already an indirect dependency of `volcalc` through its dependency on `ChemmineR`.
Adding an argument to our `volcalc` function to specify the input format, and passing it to `ChemmineOB`'s translation function would be a way to expand the usability of `volcalc` even further.
