# Requirements
<!-- 
An idea of what is required to make the project actually happen
-->

## People
<!--
Who needs to be involved, what's the proposed structure, what will it take to get their involvement?
-->

Kristina Riemer and Eric Scott will do the coding work for this project.  Eric and Kristina both have experience creating R packages, writing tests, and collaborating using GitHub.  Eric has experience submitting packages to CRAN and with automation using GitHub actions.  

Eric and our collaborators Laura Meredith and S. Marshall Ledford have domain experience working with volatile organic compounds and chemoinformatics more generally. S. Marshall Ledford is currently the sole user of `volcalc` besides the developers, and is interested in giving feedback on future versions.

<!-- ## Processes -->
<!-- 
What processes need to be put in place e.g. codes of conduct, regular ISC meetings, handover to the community at large?
-->


<!-- ## Tools & Tech -->
<!--
What is going to be needed to deliver this project? 

Will cloud computing be used - if yes are there are necessary components that will be deciding factors between providers?

Are there tools or tech that don't exist that will be produced to facilitate the project?
-->

## Funding
<!-- 
[TO DO] THE GUIDANCE IS PRETTY UNCLEAR, ESP IN LIGHT OF GABOR'S PROPOSAL VS AWARD SIZE

-->

**Attach simplified version of sponsored projects budget** 

We would like to request funding for the salaries of personnel working on this project.

- Kristina Riemer: 100 hours, $4,791
- Eric Scott: 160 hours, $7,475

For a total of $12,265

Funding timeline:

- After milestone 2 (September 1, 2023), $6,000
- After technical delivery (January 31, 2024), $6,000

## Summary
<!--
A summary of the requirements that contextualises the costs
-->

These costs represent a one-time investment to pay for personnel to work on the project.