# Success
<!-- 
Projects should have a definition of done that is measurable, and a thorough understanding going in of what the risks are to delivery 
-->

## Definition of done
<!-- 
What does success look like? 
-->
We would consider this project successful when a new version of `volcalc` with the ability to calculate volatility given an arbitrary molfile has been released on GitHub, the code has been archived on Zenodo, and the package has been successfully submitted to CRAN.

## Measuring success
<!-- 
How will we know when success is achieved, what markers can we use along the way 
-->

The following can be used to measure success:

- Can the package be installed from GitHub? (yes/no)
- Can the package be installed from r-universe? (yes/no)
- Is there sufficient test coverage? (at least 90%)
- Are there correctness tests for volatility predictions including comparisons with measured values (± some tolerance) (yes/no)
- Is the package passing `R CMD check` on Linux, macOS, and Windows using CI? (yes/no)
- Has the package been tested by users other than the developers? (yes/no)
- Does the package have a vignette that is easy to follow? (yes/no)
- Is code archived on Zenodo and a DOI associated with the package citation? (yes/no)
- Can chemical representation types be used as input? (molfile for success; InChI, SMILES, and possibly more for reach goal)

## Future work
<!-- 
How could this be extended / developed in the future by yourself and/or the community in general?
-->

- The contribution of some functional groups to volatility were not able to be measured using existing methods. As these analytical methods improve, the algorithm in `volcalc` can be updated.
- `volcalc` only calculates relative volatility under standard conditions; functionality to specify custom environmental conditions could be added.

## Key risks
<!-- 
What sort of things could come up that can delay or break the project?

 - [ ] People
 - [ ] Processes
 - [ ] Tooling & Technology
 - [ ] Costs

-->

- The SIMPOL algorithm might not be applicable to *all* compounds, since it was designed to work with volatile organic compounds.  In that case, we may need to add a warning to the user that values returned by `volcalc` may not make sense for certain compounds based on molecular weight, for example. We will explore edge cases with our collaborators and develop a plan to guide users to correct and accurate interpretation of data returned by `volcalc` functions.
- `volcalc` has `OpenBabel` as a system dependency (indirectly), which could potentially lead to delays in getting the package to build using GitHub Actions. In the event that this is an issue, we will reach out to the rOpenSci community on Slack for help with this.
- We plan to improve and submit this package to CRAN to increase the possible userbase and its ease of use. This process can be challenging due to technical hurdles, and it is possible that this package will not ultimately be accepted. We will reach out to other R users to get their assistance to ensure the package ends up on CRAN. 
