# Project plan

## Dates

- Project start date: June 1, 2023
- Project end date: May 31, 2024

## Start-up phase
<!--
Covering the planning phase, this section should provide a relatively detailed plan of how work will start on the project. This section is important because projects need to get up and running quickly.


 - [ ] Setting up collaboration platform inc. code for contributors etc.
 - [ ] Licence decisions
 - [ ] Reporting framework
-->

#### Milestone 1: August 1, 2023

- Implement CI with GitHub actions
- Check code coverage with `codecov` package
- Use GitHub Issues or Discussions to brainstorm eventual API (e.g., function names, argument names, how many exported functions)

Estimated work: 20 hours


## Technical delivery
<!--
Covering the actual delivery of the project this section should provide at least a high-level the implementation. 

Including target dates is really important as you need to be committed and the ISC need to have a means of tracking delivery
-->

#### Milestone 2: October 1, 2023

- Re-factor `calc_vol()` code to split KEGG download and SIMPOL calculation functionality
- Implement user inputs for environment (soil, water) and volatility categories
- Deprecate arguments and functions appropriately as necessary
- Update documentation to reflect new function usage

Estimated work: 70 hours


#### Milestone 3: February 1, 2024

- Create a vignette demonstrating both KEGG usage and more general usage (i.e., providing a path to a molfile) for volatility estimation
- Improve package documentation by adding citations, details, and additional examples where appropriate
- Create a `pkgdown` website for `volcalc`
- Create a CITATION.cff file, make a GitHub release, and archive code on Zenodo
- Go through checklist generated by `usethis::use_release_issue()` in preparation for CRAN submission

Estimated work: 70 hours


#### Milestone 4: May 1, 2024

- Add functionality to supply other chemical representations besides molfiles as input
- Add to vignette(s) examples of integrating `volcalc` with data sources such as the `webchem` package to estimate volatility for an arbitrary set of compounds (i.e., not from KEGG)

Estimated work: 80 hours


## Other aspects
<!--
Covering non-technical activities like on-going publicity, paper preparation, discussion groups etc. that might be required to facilitate successful delivery of the project.

 - [ ] Announcement post
 - [ ] Delivery blog post
 - [ ] Twitter
 - [ ] UseR!
 - [ ] ISC meetings
-->

Dissemination plan: <!-- This section is done! -->

- After the initial re-factor (milestone 2 above), we plan to share the package with `webchem` contributors via our rOpenSci Slack channel for feedback & suggestions.  We will encourage them to share the project with their networks of collaborators as well.
- Near the project conclusion we will:
  - prepare a blog post for https://datascience.cct.arizona.edu/
  - prepare a Twitter announcement to share from [\@cct_datascience](https://twitter.com/cct_datascience)
  - prepare a short demonstration video to be published to our [YouTube channel](https://www.youtube.com/@cctdatascience2556) that can be shared on the package README and through social media
  - work with our collaborator Laura Meredith to identify potential domain-specific venues to promote the use of `volcalc` including virtual training workshops, international scientific conferences, email lists, lab website, and social media accounts

Estimated work: 20 hours