on:
  push:
    branches: [main, master]

name: render-proposal

jobs:
  render-proposal:
    runs-on: ubuntu-latest
    container: rocker/r-rmd
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Setup Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        with:
          tinytex: true
          
      - name: Render Proposal
        uses: quarto-dev/quarto-actions/render@v2
        with:
          to: html
          path: "isc-proposal.Qmd"